version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_UN}
      POSTGRES_PASSWORD: ${DATABASE_PW}
      POSTGRES_DB: coffeescraper
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

